apiVersion: apps/v1
kind: Deployment
metadata:
name: welcomeapi-deployment
labels:
app: welcomeapi
spec:
replicas: 2
selector:
matchLabels:
app: welcomeapi
template:
metadata:
labels:
app: welcomeapi
spec:
containers:
- name: welcomeapi
image: welcomeapi:latest
imagePullPolicy: IfNotPresent
ports:
- containerPort: 8082
---------------------

apiVersion: v1
kind: Service
metadata:
name: welcomeapi-service
spec:
selector:
app: welcomeapi
type: NodePort
ports:

* protocol: TCP
  port: 8082
  targetPort: 8082
  nodePort: 30080
