apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomeapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcomeapi
  template:
    metadata:
      labels:
        app: welcomeapi
    spec:
      containers:
        - name: welcomeapi
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: welcomeapi-service
spec:
  selector:
    app: welcomeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
