apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomeapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcomeapi
  template:
    metadata:
      labels:
        app: welcomeapi
    spec:
      containers:
        - name: welcomeapi
          image: welcomeapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: welcomeapi-service
spec:
  type: NodePort
  selector:
    app: welcomeapi
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 64725
