apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomeapi-deployment
  labels:
    app: welcomeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcomeapi
  template:
    metadata:
      labels:
        app: welcomeapi
    spec:
      containers:
        - name: welcomeapi-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: welcomeapi-service
spec:
  type: LoadBalancer
  selector:
    app: welcomeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
